#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./{{ name }}.out.%j
#SBATCH -e ./{{ name }}.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J {{ name }}
#
# Queue (Partition):
{%- if gpu %}
#SBATCH --gres=gpu:2
{%- endif %}
#
# Number of nodes and MPI tasks per node:
#SBATCH --nodes={{ n_nodes }}
#SBATCH --ntasks-per-node=32
# Wall clock limit:
#SBATCH --time={{ formatted_time }}

module purge
{%- if mdengine == 'gromacs' and version in [ '2018.1', '2016.5' ] %}
module load gcc/6.4.0
{%- endif %}
{%- if gpu %}
{%- if mdengine == 'gromacs' and version in [ '2018.1', '2018', '2016.5' ] %}
module load cuda/9.0.176
{%- elif mdengine == 'gromacs' and version in [ '2016.3', '5.1.4', '5.0.7' ] %}
module load cuda/8.0.44
{%- endif %}
{%- endif %}
module load {{ module }}

# Run {{ module }} for {{ time  }} minutes
{%- if mdengine == "gromacs" %}
srun gmx_mpi mdrun -v -resethway -maxh {{ time / 60 }} -deffnm {{ name }}
{%- elif mdengine == "namd" %}
srun namd2 {{ name }}.namd
{%- endif %}
